shopproject/cartapp/urls.py
from django.urls import path
from .import views
app_name = 'cartapp'

urlpatterns = [
    path('add/<int:pr_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:pr_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:pr_id>/',views.full_remove,name='full_remove'),
    ]

shopproject/searchapp/urls.py
from django.urls import path
from .import views
app_name = 'searchapp'

urlpatterns = [
    path('',views.searchresult,name='searchresult'),
    ]

shopproject/shopapp/urls.py
from django.urls import path
from .import views
app_name = 'shopapp'

urlpatterns = [
    path('',views.allcat,name='allcat'),
    path('<slug:c_slug>/',views.allcat,name='allpro'),
    path('<slug:c_slug>/<slug:pro_slug>/',views.prodetails,name='pdetails')
]

shopproject/shopproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include("shopapp.urls")),
    path('search/',include("searchapp.urls")),
    path('cart/',include("cartapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopproject/cartapp/models.py
from django.db import models
from shopapp.models import product

# Create your models here.
class Cart(models.Model):
    c_id=models.CharField(max_length=250,blank=True)
    date_add=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_add']
    def __str__(self):
        return '{}'.format(self.c_id)


class CartItem(models.Model):
    prod=models.ForeignKey(product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.prod.price* self.quantity

    def __str__(self):
        return '{}'.format(self.prod)

shopproject/searchapp/models.py
from django.db import models

# Create your models here.

shopproject/shopapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    des = models.TextField(blank=True)
    img = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shopapp:allpro',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    des = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(category, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'


    def get_url(self):
        return reverse('shopapp:pdetails',args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

shopproject/cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shopapp.models import product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,pr_id):
    pr=product.objects.get(id=pr_id)
    try:
        cart=Cart.objects.get(c_id=cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(c_id=cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(prod=pr,cart=cart)
        if cart_item.quantity < cart_item.prod.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(prod=pr,quantity=1,cart=cart)
        cart_item.save()
    return redirect('cartapp:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(c_id=cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.prod.price * cart_item.quantity)
            counter +=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,pr_id):
    cart=Cart.objects.get(c_id=cart_id(request))
    produc = get_object_or_404(product,id=pr_id)
    cart_item=CartItem.objects.get(prod=produc,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cartapp:cart_detail')

def full_remove(request,pr_id):
    cart = Cart.objects.get(c_id=cart_id(request))
    produc = get_object_or_404(product, id=pr_id)
    cart_item = CartItem.objects.get(prod=produc, cart=cart)
    cart_item.delete()
    return redirect('cartapp:cart_detail')

shopproject/searchapp/views.py
from django.shortcuts import render
from shopapp.models import product
from django.db.models import Q
# Create your views here.
def searchresult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=product.objects.all().filter(Q(name__contains=query) | Q(des__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

shopproject/shopapp/views.py
from django.shortcuts import render, get_object_or_404
from  .models import product,category
from django.core.paginator import Paginator,InvalidPage,EmptyPage

# Create your views here.
def allcat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug != None:
        c_page=get_object_or_404(category,slug=c_slug)
        products_list=product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products':products})

def prodetails(request,c_slug,pro_slug):
    try:
        pro=product.objects.get(category__slug=c_slug,slug=pro_slug)
    except Exception as e:
        raise e
    return render(request,"product.html",{'pro':pro})

shopproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <meta name="description" content="{% block metadescription %} {% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'https://fonts.googleapis.com/css2?family=Alfa+Slab+One&display=swap' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js">
    </script>
    <title>{% block title %}
        {% endblock %}</title>
</head>
<body>
<div>
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}

  </div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

shopproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
  elcome to cart....Proceed to buy Your fav dish
{% endblock %}

{% block title %}
    Cart
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Cart is Empty

        </h1>
        <br>
        <p class="text-center"> Please Click <a href="{% url 'shopapp:allcat' %}">Here</a> to continue</p>
    </div>
</div>
{% else %}
<div>
    <div>
        <br>
        <h1 class="text-center my_title"> YOUR CART</h1>
    </div>

    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 text-center">
            <table class="table my_custom_table" style="width:50%;float:left">
                <thead class="my_thead">
                    <tr>
                        <th colspan="5"> Your Items</th>
                    </tr>

                </thead>

                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                    <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.prod.img.url}}" alt="" style="width:100px;" class="float-left rounded custom-image"></a>
                    </td>
                    <td>
                        {{cart_item.prod.name}}
                        <br>

                      SKU:{{cart_item.prod.id}}
                        <br>
                        Price:${{cart_item.prod.price}}
                        <br>
                        QTY:{{cart_item.quantity}} X {{cart_item}}
                    </td>
                    <td>
                        {{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.prod.stock %}
                    <td>
                        <a href="{% url 'cartapp:add_cart' cart_item.prod.id %}" class="custom_a"> <i class="fa fa-plus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cartapp:cart_remove' cart_item.prod.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cartapp:full_remove' cart_item.prod.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>

                    </td>
                    {% else %}

                        &nbsp;<a href="{% url 'cartapp:cart_remove' cart_item.prod.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cartapp:full_remove' cart_item.prod.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>



        <table class="table my_custom_table" style="width:50%;float:right;">
            <thead class="my_custom_thead">
            <tr>
                <th style="background-color:yellow;">
                    CHECKOUT
                </th>
            </tr>

            </thead>
            <tbody>
            <tr>
                <td>
                    Please review Your cart Item Before Payment.
                </td>
            </tr>
            <tr>
                <td>
                    Total Amount ₹ {{total}}
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shopapp:allcat' %}" class="btn btn-warning btn-block my-custom-button">Continue </a>
        </div>
    </div>
</div>
{% endif %}
</div>
</div>
{% endblock %}

shopproject/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {% if category %}
        {{ category.des|truncatewords:155 }}
    {% else %}
        Welcome to ANNEX Online Shopping .... Let's see our new product
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{category.name}}
    {% else %}
        Welcome ...Go for differnt item
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div>
            <div class="row my_row">
                <div class="mx-auto">
                <h1 style="color:red;text-align:center;">All {{category.name}} Products</h1>
            </div>
                </div>
        </div>
    {% endif %}
        <div class="row mx-auto">
            {% if category %}
                <img class="my_image my_image_padding" src="{{category.img.url}}" alt="{{category.name}}">
            <br>
        </div>
            <br>
        <div>
            <h2 class="text-center my_title">{{category.name}}</h2>
            <p class="text-justify parag">{{category.des}}</p>
        </div>
            {% else %}
<center>
                <div>
                   <center> <img class="my_image my_image_padding"  src="{% static 'img/banne.png' %}" alt="Our products" style="width:75%;height:auto;" ></center>
                </div>
    </center>
                    <br>
                <div>
                    <h2 class="text-center my_title">Our Collections</h2>
                    <br>
                    <p class="parag">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div>
<br><br>
            {% endif %}
                <div class="container">
                    <div class="row mx-auto">
                        {% for pro in products.object_list %}
                            <div class="my_bottom_margin  col-sm-12 col-md-4 col-lg-4">

                                <div class="card mt-5 text-center my_card" style="max-width:70rem;">
                                    <div>
<div>
                                    <a href="{{pro.get_url}}"><img class="card-image-top my-image" src="{{pro.img.url}}" alt="{{pro.name}}" style="width:350px;height:250px"></a>
                                    <div class="card-body">
                                        <h2>{{pro.name}}</h2>
                                        <h4>{{pro.price}}</h4>

</div>
                                    </div>
                                        </div>
                                </div>

                            </div>
                        {% endfor %}

                    </div>
                    <div class="mx-auto">
                        {% if products.paginator.num_pages > 1 %}

                        <hr>
                        <div class="text-center">

                            {% for pg in products.paginator.page_range %}
                            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                    <br>
                </div>

{% endblock %}

shopproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">

    <p class="text-center" style="color:white">@ All product. inc all rights reserved.</p>

</div>

shopproject/templates/header.html
{% load static %}
<header>
    <center>
      <a href="{% url 'shopapp:allcat' %}" ><img src="{% static 'img/log.png' %}" alt="LogoImage" width="350" height="300px"></a>
    </center>
</header>

shopproject/templates/navbar.html
<center><nav class="navbar navbar-expand-lg navbar-dark bg-success" style="width:2000px;height:95px;">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shopapp:allcat' %}">Home</a>
        </li>

        <li class="nav-item dropdown {% if 'shopaap' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            ITEMS
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a class="dropdown-item" href="{% url 'shopapp:allcat' %}">ALL ITEMS</a></li>
            {% for ca in links %}
            <li><a class="dropdown-item" href="{{ca.get_url}}">{{ca.name}}</a></li>
            {% endfor %}

          </ul>
        </li>

         <li class="nav-item">
        <a class="nav-link" href="{% url 'cartapp:cart_detail' %}"><i class="fa fa-shopping-cart"></i>({{item_count}})</a>
      </li>
      </ul>

      <form class="d-flex" method="get" action="{% url 'searchapp:searchresult' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-warning" type="submit"><i class="fa fa-search"></i></button>
      </form>

    </div>
  </div>
</nav>
  </center>

shopproject/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {
        {{ Pro.des|truncatewords:155 }}
{% endblock %}

{% block title %}
        {{pro.name}}
{% endblock %}

{% block content %}
<center>
<div>
    <div>
        <br><br>
        <p><a href="{% url 'shopapp:allcat' %}">HOME</a>  <a href="{{pro.category.get_url}}">{{pro.category}}</a>  {{pro.name}} </p>
    </div>
</div>
<div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-12">
        <div style="min-width:18rem;">
            <img src="{{pro.img.url}}" alt="{{pro.name}}" class="my_img">
        </div>
    </div>
    <div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-12">
            <h1>{{pro.name}}</h1>
            <p>{{pro.des}}</p>
            <h4><b>${{pro.price}}</b></h4>
            <p><b>Product Description-</b>{{pro.des}}</p>
            <br>
            {% if pro.stock <= 0 %}
            <h2 style="color:red"><b>SORRY..Not available.</b></h2>
            {% else %}
          <h4 style="font-size:25px;">  <a href="{% url 'cartapp:add_cart' pro.id %}" class="btn btn-warning"><b>Add to Cart</b></a></h4>
            {% endif %}
        </div>
    </div>
</div>
<br><br>
</center>
{% endblock %}

shopproject/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}

        Welcome to ANNEX Kitchen .... We have delicious dishes....Book it, pick it and lick it

{% endblock %}
{% block title %}
Search
{% endblock %}
{% block content %}
<div>
  <p class="text-center my_search">Your result is here....<b>"{{query}}"</b></p>
</div>
 <div class="row mx-auto">
                        {% for pro in products %}
                            <div class="my_bottom_margin  col-sm-12 col-md-4 col-lg-4">

                                <div class="card text-center my_card" style="min-width:16rem">
                                    <div>
<div>
                                    <a href="{{pro.get_url}}"><img class="card-image-top my-image" src="{{pro.img.url}}" alt="{{pro.name}}"></a>
                                    <div class="card-body">
                                        <h2>{{pro.name}}</h2>
                                        <h4>{{pro.price}}</h4>

                                    </div>
                                    </div>
                                        </div>
                                </div>

                            </div>
     {% empty %}
     <div class="mx-auto">
         <p class="text-center my_search">0 results Found</p>
     </div>
     {% endfor %}
 </div>

{% endblock %}